modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="LGPL"

[[mods]] #mandatory
modId="rubidium_extras" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Rubidium Extras" #mandatory
logoFile= "icon.png" #optional
credits="TeamDeusVult" #optional
authors="TexTrue,TexStudio-i18nProject" #optional
description='''
Rubidium-Extras Mod
'''

[[dependencies.rubidium_extras]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.rubidium_extras]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
